#spring.cloud.config.server.git.uri=C:\Users\vijay\OneDrive\Desktop\config-repo
#spring.cloud.config.server.git.uri=${HOME}\config-repo
#spring.cloud.config.server.git.uri=C:\\\\Users\\\\vijay\\\\OneDrive\\\\Desktop\\\\config-repo\\\\
#spring.cloud.config.server.git.uri:file:///${user.home}/config-repo/
#spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
server.port: 8080
#spring.cloud.config.server.git.uri: https://github.com/marslinvijay/config-repo.git

spring:
  cloud:
    bus:
      enabled: false
    config:
      server:
        git :
          uri: https://github.com/marslinvijay/config-repo.git
---
#spring:
#  profiles: config-monitor
#  cloud:
#    bus:
#      enabled: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
    
---
spring:
  profiles: config-monitor
  cloud: 
    bus:
      enabled: true
  kafka:   
      bootstrap-servers: localhost:9092
      #key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"

db:
  connection: {url: 'http://', username: 'guest', password: 'guest'}
  host: 127.0.0.1
  port: 8095
        

#spring.rabbitmq.host: localhost
#spring.rabbitmq.port: 5672
#spring.rabbitmq.username: guest
#spring.rabbitmq.password: guest

